# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Research
    url: research
    weight: 10
  - name: News
    url: news
    weight: 20
  - name: People
    url: people
    weight: 30
#  - name: Events
#    url: event
#    weight: 40
  - name: Publications
    url: publication
    weight: 50
  - name: Resources
    url: resources
    weight: 60
    identifier: resources
  - name: Corpora
    PageRef: resources/corpora/_index.md
    weight: 10
    parent: resources
  - name: Research tools
    PageRef: resources/tools/_index.md
    weight: 20
    parent: resources
  - name: Scripts
    PageRef: resources/scripts/_index.md
    weight: 30
    parent: resources
  - name: How to's
    PageRef: resources/how-to/_index.md
    weight: 40
    parent: resources
  - name: Course materials
    PageRef: resources/course-materials/_index.md
    weight: 45
    parent: resources
  - name: Other resources
    PageRef: resources/other-resources/_index.md
    weight: 50
    parent: resources
  - name: Demos
    url: demos
    weight: 65
  - name: Contact
    url: contact
    weight: 70
